name: Release package Node.js CI

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'yarn'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@welkincloud-io'

      - name: Resolve dependencies
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Resolve dependencies
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: borales/actions-yarn@v4
        with:
          cmd: install-all

      - name: Publish packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          lerna run build
          lerna publish from-package --yes
