name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies core
        run: |
          cd packages/easy-email-core && yarn

      - name: Run tests core
        run: yarn test:core

      - name: Install dependencies extensions
        run: |
          cd packages/easy-email-extensions && yarn

      - name: Run tests extensions
        run: yarn test:extensions
