name: Release package Node.js CI

on:
  push:
    branches:
      - master


jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - easy-email-core
          - easy-email-editor
          - easy-email-extensions
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 16.x
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@welkincloud-io'

      - name: Install dependencies
        working-directory: packages/${{ matrix.package }}
        run: yarn install

      - name: Check if version has changed
        id: version-check
        working-directory: packages/${{ matrix.package }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "Current version: ${CURRENT_VERSION}"
          PUBLISHED_VERSION=$(npm show -json "@welkincloud-io/$(basename "$PWD")" version 2>/dev/null | jq -r '.version' 2>/dev/null || echo "")

          if [ -z "$PUBLISHED_VERSION" ]; then
            echo "Package doesn't exist in the registry yet."
            changed=true
          else
            echo "Published version: ${PUBLISHED_VERSION}"
            changed=$(test "$CURRENT_VERSION" != "$PUBLISHED_VERSION" && echo true || echo false)
          fi

          echo "changed=${changed}" >> $GITHUB_OUTPUT

      - name: Publish package
        if: steps.version-check.outputs.changed == 'true'
        working-directory: packages/${{ matrix.package }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ls -lh .
          npm publish