name: Release package Node.js CI

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'yarn'
          cache-dependency-path: |
            packages/easy-email-core/yarn.lock
            packages/easy-email-editor/yarn.lock
            packages/easy-email-extensions/yarn.lock
            packages/easy-email-localization/yarn.lock
          registry-url: 'https://npm.pkg.github.com'
          scope: '@welkincloud-io'

      - name: Resolve dependencies
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          #yarn cache clean
          yarn vercel-install
          yarn build

      - name: Publish packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          lerna publish from-package --yes
