name: Release package Node.js CI

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          registry-url: 'https://npm.pkg.github.com'
          scope: '@welkincloud-io'

      - name: "Setup npm"
        run: |
          npm set "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}"

      - name: Resolve dependencies
        run: |
          yarn cache clean
          yarn vercel-install
          yarn build

      - name: Publish packages
        run: |
          lerna publish from-package --yes
