name: Release package Node.js CI

on:
  push:
    branches:
      - master


jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - easy-email-core
          - easy-email-editor
          - easy-email-extensions
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 16.x
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com/'
          scope: '@welkincloud-io'

      - name: Install dependencies
        working-directory: packages/${{ matrix.package }}
        run: npm install

      - name: Authenticate with Github npm registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

      - name: Check if version has changed
        id: version-check
        working-directory: packages/${{ matrix.package }}
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          PUBLISHED_VERSION=$(npm show "$(basename "$PWD")" version)
          echo "changed=$(test "$CURRENT_VERSION" != "$PUBLISHED_VERSION" && echo true || echo false)" >> $GITHUB_OUTPUT

      - name: Publish package
        if: steps.version-check.outputs.changed == 'true'
        working-directory: packages/${{ matrix.package }}
        run: |
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}