name: Release package Node.js CI

on:
  push:
    branches:
      - master


jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - easy-email-core
          - easy-email-editor
          - easy-email-extensions
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 16.x
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@welkincloud-io'

      - name: Install dependencies
        working-directory: packages/${{ matrix.package }}
        run: yarn install

      - name: Publish package
        working-directory: packages/${{ matrix.package }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm publish